# Generated by Django 4.0.3 on 2022-06-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'basket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fbasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fbasket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gbasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gbasket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nbasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr', models.IntegerField(blank=True, null=True)),
                ('pname', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nbasket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_num', models.IntegerField(blank=True, null=True)),
                ('b_pname', models.CharField(blank=True, max_length=150, null=True)),
                ('b_price', models.IntegerField(blank=True, null=True)),
                ('g_pname', models.CharField(blank=True, max_length=150, null=True)),
                ('g_price', models.IntegerField(blank=True, null=True)),
                ('f_pname', models.CharField(blank=True, max_length=150, null=True)),
                ('f_prcie', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbasket',
                'managed': False,
            },
        ),
    ]
